name: 🐞 Bug report
description: File a bug/issue to help us improve
title: "[BUG]"
labels: [bug, needs-triage]
body:
  - type: checkboxes
    attributes:
      label: Is there an existing issue for this?
      description: Please search to see if an issue already exists for the bug you encountered.
      options:
        - label: I have searched the existing issues
          required: true
  - type: input
    attributes:
      label: What version of sap-iac are you using?
      placeholder: "0.1.0"
    validations:
      required: true
  - type: textarea
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected behavior
      description: What you expected to happen.
  - type: textarea
    attributes:
      label: Steps to reproduce
      placeholder: |
        1. Run `sap-iac init ...`
        2. ...
  - type: textarea
    attributes:
      label: Additional context
